repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: stable
    hooks:
      - id: ruff
  - repo: https://github.com/PyCQA/pylint
    rev: stable
    hooks:
      - id: pylint

